<?php

/**
 * @file
 * Meta helper.
 *
 * @todo
 *   - Build
 *   - entity_save()
 *     - Possible to be generic?
 *     - Option to build data load (settings)
 *       - Per meta type? Or bundle?
 *   - Generic storage arbitrary data
 *     - Custom? Entity? Which controller?
 *     - Links to pages (no entity)!
 *   - Node form
 *     - New vertical tab
 *       - Per meta type?
 *   - Admin block
 *     - When entity: edit entity meta
 *     - When NOT entity: edit "page" meta
 *   - Inheritance mecanism
 *     - Chain of responsability
 *     - Merge or not?
 *     - Find nice UI concept
 */

/**
 * Cache in field is enabled.
 */
const META_CACHE_ENABLED = true;

/**
 * Meta field type and name prefix.
 */
const META_FIELD = 'meta';

/**
 * Meta entity type for non entity instances.
 */
const META_ENTITY = 'meta';

/**
 * Default filter for description.
 */
const META_FILTER = 'meta_description';

/**
 * Arbitrary weight value for first meta in HEAD.
 */
const META_WEIGHT_START = 40315;

/**
 * Custom autoloader.
 */
if (!class_exists('Meta\Node')) {
  spl_autoload_register(function ($className) {
    if (false !== strpos($className, '\\')) {
      $parts = explode('\\', $className);
      if ('Meta' === $parts[0]) {
        $filename = __DIR__ . '/lib/' . implode('/', $parts) . '.php';
        return (bool)include_once $filename;
      }
    }
    return false;
  });
}

/**
 * We need field info.
 */
require_once __DIR__ . '/meta.field.inc';

/**
 * Implements hook_menu().
 */
function meta_menu() {
  $items = array();

  $items['admin/config/services/meta'] = array(
    'title'            => "Meta",
    'description'      => "Configure entity driven meta information.",
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('meta_admin_bundle'),
    'access arguments' => array('administer site configuration'),
    'file'             => 'meta.admin.inc',
    'type'             => MENU_NORMAL_ITEM,
  );
  $items['admin/config/services/meta/bundles'] = array(
    'title'            => "Entities",
    'type'             => MENU_DEFAULT_LOCAL_TASK,
  );
  $items['admin/config/services/meta/bundles/%meta/%'] = array(
    'title'            => 'Mapping',
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('meta_mapping_form', 5, 6),
    'access arguments' => array('administer site configuration'),
    'file'             => 'meta.form.inc',
    'type'             => MENU_CALLBACK | MENU_VISIBLE_IN_BREADCRUMB,
  );

  // Custom meta entities listing.
  $items['admin/config/services/meta/misc'] = array(
    'title'            => "Others",
    'page callback'    => 'meta_admin_misc',
    'access arguments' => array('administer site configuration'),
    'file'             => 'meta.admin.inc',
    'type'             => MENU_LOCAL_TASK,
  );
  $items['admin/config/services/meta/misc/list'] = array(
    'title'            => "List",
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('meta_admin_misc_list'),
    'access arguments' => array('administer site configuration'),
    'file'             => 'meta.admin.inc',
    'type'             => MENU_LOCAL_TASK,
  );
  $items['admin/config/services/meta/misc/overview'] = array(
    'title'            => "Overview",
    'type'             => MENU_DEFAULT_LOCAL_TASK,
  );

  // Single custom meta handling (view form is edit form).
  $items['admin/config/services/meta/misc/add/%meta_bundle'] = array(
    'title'            => 'Add meta',
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('meta_admin_misc_add', 6),
    'access arguments' => array('administer site configuration'),
    'file'             => 'meta.admin.inc',
    'type'             => MENU_CALLBACK | MENU_VISIBLE_IN_BREADCRUMB,
  );
  $items['admin/config/services/meta/misc/list/%meta_object'] = array(
    'title'            => 'Edit meta',
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('meta_admin_misc_edit', 6),
    'access arguments' => array('administer site configuration'),
    'file'             => 'meta.admin.inc',
    'type'             => MENU_CALLBACK | MENU_VISIBLE_IN_BREADCRUMB,
  );
  $items['admin/config/services/meta/misc/list/%meta_object/delete'] = array(
    'title'            => 'Delete meta',
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('meta_admin_misc_delete', 6),
    'access arguments' => array('administer site configuration'),
    'file'             => 'meta.admin.inc',
    'type'             => MENU_CALLBACK | MENU_VISIBLE_IN_BREADCRUMB,
  );

  return $items;
}

/**
 * Implements hook_help().
 */
function meta_help($path, $arg) {
  switch ($path) {

    case 'admin/config/services/meta':
      $message = array();
      $message[] = t("Each line of the following table correspond to a type of meta tags attached to an entity type, bundle couple. For example, you may have the <em>HTML meta tags</em> attached to <em>page node</em> type.");
      $message[] = t("Displayed meta information into the HTML head tag will be driven by a specific mapping: the mapping will tie together entity arbitrary data (for example fields or object properties) to the targetted meta property.")
        . ' ' . t("From this administration section, you can configure the default mapping for each bundle, which then may or may be not overriden by the user in the entity form.");
      break;

    case 'admin/config/services/meta/misc':
      $message = array();
      $message[] = t("Your site may display pages where no entities are attached (for example, a <em>view</em> listing), case in which the default configured mappings can not determine data to be attached to the HTML <em>HEAD</em> tag.")
        . ' ' . t("This section of administration allows you to manually edit meta tags that will be provided to such pages. Each bundle here represents a method that allows to attach content to those pages.");
      break;
  }

  if (isset($message)) {
    return '<p>' . implode('</p><p>', $message) . '</p>';
  }
}

/**
 * Implements hook_entity_info().
 */
function meta_entity_info() {
  return meta_service_get()->getEntityInfo();
}

/**
 * Implements hook_fieldture_info().
 */
function meta_fieldture_info() {
  return meta_service_get()->getFieldtureInfo();
}

/**
 * Entity label callback for meta entities.
 */
function meta_entity_label($entity, $type) {
  if (META_ENTITY === $type) {
    $info  = entity_get_info(META_ENTITY);
    $label = $info['bundles'][$entity->bundle]['label'];
    return t("Meta tags for %target @type", array(
      '%target' => $entity->target,
      '@type'   => $entity->bundle,
    ));
  }
}

/**
 * Implements hook_theme().
 */
function meta_theme() {
  return array(
    'meta_mapping_form' => array(
      'render element' => 'form',
      'file'           => 'meta.form.inc',
    ),
  );
}

/**
 * Implements hook_hook_info().
 */
function meta_hook_info() {
  return array(
    'meta_info' => array(
      'group' => 'meta',
    ),
    'meta_info_input' => array(
      'group' => 'meta',
    ),
    'meta_info_output' => array(
      'group' => 'meta',
    ),
    'meta_info_bundle' => array(
      'group' => 'meta',
    ),
  );
}

/**
 * Meta bundle
 *
 * @param string $key
 *
 * @return BundleInterface
 */
function meta_bundle_load($key) {
  if ($bundle = meta_service_get()->getEntityBundle($key)) {
    return $bundle;
  }
  return false;
}

/**
 * Menu loader.
 *
 * @param int $id
 *
 * @return MetaEntity
 */
function meta_object_load($id) {
  if ($entity = meta_service_get()->loadEntity($id)) {
    return $entity;
  }
  return false;
}

/**
 * Menu loader.
 *
 * @param string $key
 *   Meta plugin key.
 *
 * @return array
 *   Meta info about this key.
 */
function meta_load($key) {
  if ($plugin = meta_service_get()->getPlugin($key)) {
    return $plugin;
  }
  return false;
}

/**
 * Get meta service.
 *
 * @return \Meta\Service
 */
function meta_service_get() {
  $instance = &drupal_static(__FUNCTION__);
  if (null === $instance) {
    $instance = new \Meta\Service();
  }
  return $instance;
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function meta_form_node_form_alter(&$form, &$form_state) {
  foreach (meta_service_get()->getPluginsFor('node', $form['#node']) as $plugin) {
    if ($plugin->allowsUserModifications('node', $form['#node']->type)) {
      $key = 'meta_' . $plugin->getType();
      $form[$key] = array(
        '#type'  => 'fieldset',
        '#title' => t($plugin->getLabel()),
        '#group' => 'additional_settings',
      );
    }
  }
}

/**
 * Implements hook_entity_view().
 */
function meta_entity_view($entity, $type, $view_mode, $langcode) {
  // Ensure we are viewing the piece of content in full page.
  if (($uri = entity_uri($type, $entity)) || $uri['path'] !== current_path()) {
    $service = meta_service_get();
    if (META_CACHE_ENABLED) {
      // When cache mode is enabled, use the cached field values. This mode
      // ensures best performances since meta data should remain dependent
      // on node content and node content only.
      foreach ($service->getPluginsFor($type, $entity) as $plugin) {
        if ($items = field_get_items($type, $entity, $plugin->getFieldName())) {
          foreach ($items as $item) {
            if (!empty($item['data']) && ($build = unserialize($item['data']))) {
              meta_entity_display($build);
            }
          }
        }
      }
    } else {
      // When cache mode is not enabled then compute everything everytime the
      // content is being viewed. For sites with no logged in users this is
      // probably a very good default since pages will be cached instead.
      foreach ($service->getPluginsFor($type, $entity) as $plugin) {
        if ($nodes = meta_entity_process($plugin, $type, $entity)) {
          if ($build = meta_entity_build($nodes)) {
            meta_entity_display($build);
          }
        }
      }
    }
  }
}

/**
 * Implements hook_entity_presave().
 */
function meta_entity_presave($entity, $type) {
  $service = meta_service_get();
  if (META_CACHE_ENABLED) {
    foreach ($service->getPluginsFor($type, $entity) as $plugin) {
      if ($nodes = meta_entity_process($plugin, $type, $entity)) {
        if ($build = meta_entity_build($nodes)) {
          $entity->{$plugin->getFieldName()} = array(LANGUAGE_NONE => array(0 => array('data' => serialize($build))));
        }
      }
    }
  }
}

/**
 * From the given nodes get the meta build array.
 *
 * @param \Meta\Node[] $nodes
 *   Nodes.
 *
 * @return array
 *   drupal_render() and drupal_add_html_head() friendly array.
 */
function meta_entity_build(array $nodes) {
  static $count = 0; // Static because we might have some on the same page.
  $ret = array();
  foreach ($nodes as $node) {
    foreach ($node->build() as $build) {
      $build['#weight'] = META_WEIGHT_START + (++$count);
      $ret['meta' . $count] = $build;
    }
  }
  return $ret;
}

/**
 * Set real meta headers.
 *
 * @param array[] $items
 *   Set of values for drupal_add_html_head().
 */
function meta_entity_display(array $items) {
  foreach ($items as $key => $build) {
    drupal_add_html_head($build, $key);
  }
}

/**
 * Build meta for given entity
 *
 * @param \Meta\PluginInterface $plugin
 *   Plugin.
 * @param string $type
 *   Entity type.
 * @param object $entity
 *   Entity.
 *
 * @return \Meta\Node[]
 *   Tree of meta nodes.
 */
function meta_entity_process(\Meta\PluginInterface $plugin, $type, $entity) {

  list(,, $bundle) = entity_extract_ids($type, $entity);

  $service = $plugin->getService();
  $nodes   = array();

  if ($mapping = $plugin->getMapping($type, $bundle)) {

    // @todo This code should be moved out.
    $properties = $plugin->getPropertyList();

    foreach ($mapping as $item) {

      if (!isset($properties[$item['name']])) {
        continue; // Unsupported item, drop it.
      }

      if (isset($properties[$item['name']]['output'])) {
        $outputKeys = $properties[$item['name']]['output'];
      } else {
        $outputKeys = array('scalar');
      }

      list($inputKey, $name) = explode(':', $item['input']);
      if (!$input = $service->getInput($inputKey)) {
        continue; // Could not find input instance, drop it.
      }
      if (!$datatype = $service->getInputDatatype($inputKey)) {
        continue; // No datatype provided.
      }

      if (!$output = $service->getOutputFor($datatype, $outputKeys)) {
        continue; // Could not find output instance, drop it.
      }

      $newNodes = $output->buildNode(
        $datatype,
        $input->getAll($name, $type, $entity),
        $output->getDefaultOptions()
      );

      // @todo Options.
      foreach ($newNodes as $node) {
        $node->setName($item['name']);
        $nodes[] = $node;
      }
    }
  }

  return $nodes;
}
